= Overview of Neo4j 4.x: Summary
:slug: 03-overview40-summary
:doctype: book
:toc: left
:toclevels: 3
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-certificate:
:page-module-duration-minutes: 5

== Course Summary

In this course, you have learned how to:

[square]
* Describe what a graph database is.
* Describe the Neo4j Graph Platform and its components.

ifdef::env-slides[]
== Resources - 1
endif::[]

ifndef::env-slides[]
== Resources
endif::[]

There are link:https://neo4j.com/developer/resources/[many resources available to you^] for learning more about Neo4j and Cypher.


* Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users: +
  https://community.neo4j.com

* Neo4j documentation: +
  https://neo4j.com/docs/

ifdef::env-slides[]
== Resources - 2
endif::[]

* Neo4j Sandboxes for experimenting with graphs: +
  https://sandbox.neo4j.com/?ref=graph-academy

* Videos on  the Neo4j YouTube channel: +
  https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

* Neo4j online and classroom training: +
  https://neo4j.com/graphacademy/

ifdef::env-slides[]
== Resources - 3
endif::[]


* GitHub repository: +
  https://github.com/neo4j-contrib

* Neo4j events all over the world: +
  https://neo4j.com/events/world/all/

ifdef::env-slides[]
== Resources - 4
endif::[]

* Graph Gists for learning more use cases for Neo4j: +
  https://neo4j.com/graphgists/

* Attend a Neo4j meetup: +
  https://www.meetup.com/topics/neo4j/

* View questions/answers raised about Neo4j: +
  https://stackoverflow.com/tags/neo4j/hot


== Next Steps

Now that you have completed the Overview of Neo4j 4.x Course, you can progress to the link:https://neo4j.com/graphacademy/training-querying-40/enrollment/[Querying with Cypher in Neo4j 4.x^] course.
This course teaches you the Cypher syntax for querying the database and contains numerous hands-on exercises.

link:https://neo4j.com/graphacademy/training-querying-40/enrollment/[Progress to Querying with Cypher in Neo4j 4.x^, role=button]

== Neo4j Certification

Take the link:https://neo4j.com/graphacademy/neo4j-certification/[Neo4j Certified Professional exam] to gain your certificate.
This certification exam tests you on content from courses, _Introduction to Neo4j 4.0_ or _Introduction to Neo4j 3.5_.
You can take the certification exam multiple times until you pass!


ifndef::env-slides[]
== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.
endif::[]
