= Graph Data Modeling for Neo4j: Summary
:slug: 06-graph-data-modeling-summary
:doctype: book
:toc: left
:toclevels: 3
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-certificate:
:page-module-duration-minutes: 5

== Course Summary

In this course, you have learned how to:

[square]
* Describe what a graph data model is for a Neo4j database.
* Design an initial graph data model using Neo4j best practices.
* Describe the core principles used for Neo4j graph data modeling.
* Describe the common structures used in a Neo4j graph data model.
* Refactor and evolve a graph data model.

ifdef::env-slides[]
== Resources - 1
endif::[]

ifndef::env-slides[]
== Resources
endif::[]

There are link:https://neo4j.com/developer/resources/[many resources available to you^] for learning more about Neo4j and Cypher.


* Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users: +
  https://community.neo4j.com

* Neo4j documentation: +
  https://neo4j.com/docs/

ifdef::env-slides[]
== Resources - 2
endif::[]

* Neo4j Sandboxes for experimenting with graphs: +
  https://sandbox.neo4j.com/?ref=graph-academy

* Videos on  the Neo4j YouTube channel: +
  https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

* Neo4j online and classroom training: +
  https://neo4j.com/graphacademy/

ifdef::env-slides[]
== Resources - 3
endif::[]


* GitHub repository: +
  https://github.com/neo4j-contrib

* Neo4j events all over the world: +
  https://neo4j.com/events/world/all/

ifdef::env-slides[]
== Resources - 4
endif::[]

* Graph Gists for learning more use cases for Neo4j: +
  https://neo4j.com/graphgists/

* Attend a Neo4j meetup: +
  https://www.meetup.com/topics/neo4j/

* View questions/answers raised about Neo4j: +****
  https://stackoverflow.com/tags/neo4j/hot


== Next Steps

Now that you have completed the _Graph Data Modeling with Neo4j_ Course, you can progress to the link:https://neo4j.com/graphacademy/training-igdm-40/enrollment/[Implementing Graph Data Models in Neo4j 4.x^]
 course.
This course teaches you how import data into a graph that supports a starting graph data model, evolve the data in the graph to support changes to the model,  and contains numerous hands-on exercises.

https://neo4j.com/graphacademy/training-igdm-40/enrollment/[Progress to Implementing Graph Data Models in Neo4j 4.x^,role=button]

== Neo4j Certification

Take the link:https://neo4j.com/graphacademy/neo4j-certification/[Neo4j Certified Professional exam] to gain your certificate.
This certification exam tests you on content from the courses in the _Introduction to Neo4j 4.x Series_.
You can take the certification exam multiple times until you pass!

link:https://neo4j.com/graphacademy/neo4j-certification/[Take the Neo4j Certified Professional exam^, role=button]


ifndef::env-slides[]
== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.
endif::[]
