= Summary: Cypher Query Tuning with Neo4j 4.x
:slug: 06-cqt-40-summary
:doctype: book
:toc: left
:toclevels: 3
:page-slug: {slug}
:page-layout: training
:page-certificate:
:page-module-duration-minutes: 5

== Course Summary

In this course, you have learned:

[square]
* How Queries Work in Neo4j
* Preparing for Query Tuning
* Reducing Cardinality
* Optimizing Property Access
* Monitoring Queries

ifdef::env-slides[]
== Resources - 1
endif::[]

ifndef::env-slides[]
== Resources
endif::[]

There are link:https://neo4j.com/developer/resources/[many resources available to you^] for learning more about Neo4j and Cypher.


* Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users: +
  https://community.neo4j.com

* Neo4j documentation: +
  https://neo4j.com/docs/

ifdef::env-slides[]
== Resources - 2
endif::[]

* Neo4j Sandboxes for experimenting with graphs: +
  https://sandbox.neo4j.com/?ref=graph-academy

* Videos on  the Neo4j YouTube channel: +
  https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

* Neo4j online and classroom training: +
  https://neo4j.com/graphacademy/

ifdef::env-slides[]
== Resources - 3
endif::[]


* GitHub repository: +
  https://github.com/neo4j-contrib

* Neo4j events all over the world: +
  https://neo4j.com/events/world/all/

ifdef::env-slides[]
== Resources - 4
endif::[]

* Graph Gists for learning more use cases for Neo4j: +
  https://neo4j.com/graphgists/

* Attend a Neo4j meetup: +
  https://www.meetup.com/topics/neo4j/

* View questions/answers raised about Neo4j: +
  https://stackoverflow.com/tags/neo4j/hot


== Next Steps

Now that you have completed the _Cypher Query Tuning with Neo4j 4.x_ Course, you can take any of these other courses:


link:https://neo4j.com/graphacademy/training-iga-40/enrollment/[Introduction to Graph Algorithms in Neo4j 4.x^]

link:https://neo4j.com/graphacademy/training-gdsds-40/enrollment/[Using a Machine Learning Workflow for Link Prediction^]

link:https://neo4j.com/graphacademy/training-gdsaa-40/enrollment/[Applied Graph Data Science for Web Applications^]

link:https://neo4j.com/graphacademy/training-graphql-apis/enrollment/[Building GraphQL APIs Using The Neo4j GraphQL Library^]

link:https://neo4j.com/graphacademy/training-basic-admin-40/enrollment/[Basic Neo4j 4.x Administration^]

== Neo4j Certification

Take the link:https://neo4j.com/graphacademy/neo4j-certification/[Neo4j Certified Professional exam] to gain your certificate.
This certification exam tests you on content from the courses in the _Introduction to Neo4j 4.x Series_.
You can take the certification exam multiple times until you pass!

link:https://neo4j.com/graphacademy/neo4j-certification/[Take the Neo4j Certified Professional exam^, role=button]


ifndef::env-slides[]
== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.
endif::[]

